### ISSUE TITLE
Is anyone still working on this?

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#940]
Wanted to give it a try again after shelving it for a while, but it doesn't look like Nevenz has done any work on Orgzly for the last several months. Anyone know what happened? Does anyone maintain their own copy?

**Comment by nevenz** [comment]
Working on it, I just don't have that much time for GitHub these days.

I've pushed the latest changes now.

**Comment by MisterY** [comment]
Just some housekeeping - @keithcrone, does the issue still need to be open?

**Comment by hugovdm** [comment]
Is there a way to virtually "buy @nevenz a coffee" as a thanks for this app? Seems to be a labour of love? 😊
